# Generated by Django 4.0.5 on 2022-06-02 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=70)),
                ('correo', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=30)),
                ('fecha_caducidad', models.DateField()),
                ('marca', models.CharField(max_length=45)),
                ('stock', models.PositiveSmallIntegerField()),
                ('precio', models.PositiveSmallIntegerField()),
                ('idEstado_Medicamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medicamentos.estado_medicamento')),
                ('idProovedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medicamentos.proovedor')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
                ('idMedicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento')),
            ],
        ),
    ]
